namespace MiniMock.Builders;

using System;
using System.Linq;
using Microsoft.CodeAnalysis;

public static class MockClassBuilder
{
    public static string Build(ISymbol?[] typeSymbols, SourceProductionContext context)
    {
        var builder = new CodeBuilder();

        builder.Add($$"""
                     // Generated by MiniMock on {{DateTime.Now}}
                     #nullable enable
                     namespace MiniMock {
                     ->
                     
                     public class Mock {
                     ->
                     """);

        foreach (var symbol in typeSymbols.OfType<INamedTypeSymbol>())
        {
            var typeArguments = symbol.TypeArguments;
            var containingNamespace = symbol.ContainingNamespace;
            var symbolName = symbol.Name;

            if (typeArguments.Length > 0)
            {
                var types = string.Join("_", typeArguments.Select(t => t.Name));
                var name = $"{symbolName}Mock_{types}";
                var methodName = symbolName + "_" + types;
                builder.Add($"internal static {symbol} {methodName}(System.Action<{containingNamespace}.{name}.Config>? mock = null) => {containingNamespace}.{name}.Create(mock);");
            }
            else
            {
                var name = symbolName + "Mock";
                var methodName = symbolName;
                builder.Add($"internal static {symbol} {methodName}(System.Action<{containingNamespace}.{name}.Config>? mock = null) => {containingNamespace}.{name}.Create(mock);");
            }
        }

        builder.Add("""
                   <-
                   }
                   <-
                   }
                   """);

        return builder.ToString();
    }
}
